name: myfinnapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  google_fonts: ^3.0.1
  convex_bottom_bar: ^3.1.0
  shared_preferences: ^2.0.15
  intl: 0.17.0
  path_provider: ^2.0.11
  get_storage: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  dropdown_search: 3.0.1
  sliver_header_delegate: 0.0.5
  flutter_svg: 1.0.3
  animated_text_kit: 3.1.2
  graphic: 0.10.7
  fl_chart: 0.55.2
  badges: 2.0.3
  image_picker: 0.8.6
  firebase_storage: 10.3.11
  firebase_core: 1.24.0
  week_of_year: 2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
