name: myfinnapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  flutter_secure_storage: 6.0.0
  google_fonts: 3.0.1
  convex_bottom_bar: 3.0.0
  shared_preferences: 2.0.15
  intl: 0.17.0
  path_provider: 2.0.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
